# Generated by Django 4.2.4 on 2023-08-30 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200, verbose_name='name of list')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='item name')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity of item')),
                ('bought', models.BooleanField(verbose_name='is item bought')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppinglist.list')),
            ],
        ),
    ]
