# Generated by Django 4.2.4 on 2023-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinglist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='bought',
            field=models.BooleanField(default=False, verbose_name='is item bought'),
        ),
    ]
